name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        arch: [32, 64]
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          ./main.sh --arch ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: MinGW${{ matrix.arch }}
          path: dist/*.7z

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.7z
