name: Build and Release Raylib with MinGW

on:
  workflow_dispatch:
  push:
    tags: [ "v*" ]

jobs:
  build:
    strategy:
      matrix:
        arch: [i686, x86_64]
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download MinGW-w64
      run: |
        $arch = "${{ matrix.arch }}"
        if ($arch -eq "i686") {
          $mingwUrl = "https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/i686-15.1.0-release-posix-dwarf-msvcrt-rt_v12-rev0.7z"
          $mingwDir = "mingw32"
        } else {
          $mingwUrl = "https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/x86_64-15.1.0-release-posix-seh-msvcrt-rt_v12-rev0.7z"
          $mingwDir = "mingw64"
        }
        Invoke-WebRequest -Uri $mingwUrl -OutFile "mingw.7z"
        echo "MINGW_DIR=$mingwDir" >> $env:GITHUB_ENV

    - name: Install 7-Zip
      run: choco install 7zip -y

    - name: Extract MinGW
      run: 7z x mingw.7z -o"$env:MINGW_DIR"

    - name: Add MinGW to PATH
      run: |
        $mingwPath = "$pwd\$env:MINGW_DIR\bin"
        echo "$mingwPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Verify GCC version
      run: gcc --version

    - name: Clone Raylib source
      run: |
        git clone --depth 1 --branch 5.0 https://github.com/raysan5/raylib.git

    - name: Build Raylib
      run: |
        cd raylib/src
        # 编译静态库
        make PLATFORM=PLATFORM_DESKTOP CC=gcc RAYLIB_LIBTYPE=STATIC -j4
        # 编译动态库
        make PLATFORM=PLATFORM_DESKTOP CC=gcc RAYLIB_LIBTYPE=SHARED -j4
        Rename-Item -Path "raylib/src/libraylibdll.a" -NewName "raylib.a"

    - name: Create package
      run: |
        $arch = "${{ matrix.arch }}"
        mkdir "raylib_$arch"
        mkdir "raylib_$arch/include"
        mkdir "raylib_$arch/lib"
        mkdir "raylib_$arch/bin"
        
        # 复制头文件
        copy raylib/src/raylib.h "raylib_$arch/include"
        copy raylib/src/raymath.h "raylib_$arch/include"
        copy raylib/src/rlgl.h "raylib_$arch/include"
        
        # 复制静态库
        copy raylib/src/libraylib.a "raylib_$arch/lib"
        
        # 复制动态库和相关文件
        ls raylib/src/
        copy raylib/src/raylib.dll "raylib_$arch/bin"
        #copy raylib/src/raylib.dll.def "raylib_$arch/lib"
        copy raylib/src/raylib.a "raylib_$arch/lib"
        
        # 创建版本文件
        echo "Raylib 5.0 built with MinGW-w64 GCC 15.1.0 ($arch)" > "raylib_$arch/version.txt"
        echo "Build date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" >> "raylib_$arch/version.txt"

    - name: Zip package
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r "raylib_mingw_${{ matrix.arch }}.zip" "raylib_${{ matrix.arch }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: raylib-mingw-${{ matrix.arch }}
        path: raylib_mingw_${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: "Raylib MinGW-w64 Build"
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/raylib-mingw-i686/raylib_mingw_i686.zip
        asset_name: raylib_mingw_i686.zip
        asset_content_type: application/zip

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/raylib-mingw-x86_64/raylib_mingw_x86_64.zip
        asset_name: raylib_mingw_x86_64.zip
        asset_content_type: application/zip
